// Generated by BUCKLESCRIPT VERSION 1.9.1, PLEASE EDIT WITH CARE
'use strict';

var Block       = require("bs-platform/lib/js/block.js");
var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statefulComponent("Greeting");

function make(name, _) {
  var click = function (_, param) {
    return /* Update */Block.__(0, [param[/* state */4] + 1 | 0]);
  };
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (param) {
      var greeting = "Hello " + (String(name) + (", You\'ve clicked the button " + (String(param[/* state */4]) + " times(s)!")));
      return React.createElement("button", {
                  onClick: Curry._1(param[/* update */1], click)
                }, greeting);
    });
  newrecord[/* initialState */10] = (function () {
      return 0;
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
